### ISSUE TITLE
Make bundle for hacking

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/express-service#2]
Instead of hacking directly in dist/service.js just replace individual files

**Comment by susan92** [comment]
I hired leehacks92@gmail.com  Professional, Skilled and perfect hackers for hire. He's the real deal. 
My husband was a serial cheater, Had to save myself and the kids so I hired him and I felt a bit skeptical but I paid and everything turned out perfect.
They hack email passwords, Social networks , Whats'app conversations, Cellphones, Any os .Clear criminal records, Change university grades, Improve credit rating , Bank transfers.
Contact them also for any general hacking services and you won’t be disappointed
